apiVersion: apps/v1
kind: Deployment
metadata:
  name: nominatim-save-service
  labels:
    app: nominatim-save-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nominatim-save-service
  template:
    metadata:
      labels:
        app: nominatim-save-service
    spec:
      containers:
        - name: nominatim-save-service
          image: gcr.io/sebastian-lauth-270621/nominatim-save-service:1
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/cloudsql/credentials.json
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.14
          command: [
            "/cloud_sql_proxy",
            "-instances=sebastian-lauth-270621:europe-west3:peakwork-db=tcp:5432",
            "-credential_file=/secrets/cloudsql/credentials.json"
          ]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
